// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID             int32
	Title          string
	Slug           string
	Summary        pgtype.Text
	Content        string
	CoverUrl       pgtype.Text
	UserID         int32
	Status         pgtype.Text
	CommentEnabled pgtype.Bool
	ViewCount      int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type ArticleCategory struct {
	ArticleID  int32
	CategoryID int32
}

type ArticleTag struct {
	ArticleID int32
	TagID     int32
}

type Category struct {
	ID          int32
	Name        string
	Slug        string
	Description pgtype.Text
	Icon        pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type Comment struct {
	ID          int32
	ArticleID   int32
	ParentID    pgtype.Int4
	UserID      pgtype.Int4
	AuthorName  pgtype.Text
	AuthorEmail pgtype.Text
	AuthorUrl   pgtype.Text
	Content     string
	Status      pgtype.Text
	IpAddress   pgtype.Text
	CreatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Menu struct {
	ID   int32
	Name string
}

type MenuItem struct {
	ID       int32
	MenuID   int32
	Name     string
	Url      string
	ParentID pgtype.Int4
	Priority pgtype.Int4
}

type Setting struct {
	Key         string
	Value       []byte
	Description pgtype.Text
}

type Tag struct {
	ID   int32
	Name string
	Slug string
	Icon pgtype.Text
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
	Avatar       pgtype.Text
	Bio          pgtype.Text
	Group        pgtype.Text
	Status       pgtype.Int4
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
