// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT COUNT(*) FROM articles WHERE deleted_at IS NULL
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesByCategory = `-- name: CountArticlesByCategory :one
SELECT COUNT(*) FROM article_categories ac
INNER JOIN articles a ON ac.article_id = a.id
WHERE ac.category_id = $1 AND a.deleted_at IS NULL
`

func (q *Queries) CountArticlesByCategory(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsByArticle = `-- name: CountCommentsByArticle :one
SELECT COUNT(*) FROM comments WHERE article_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCommentsByArticle(ctx context.Context, articleID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByArticle, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at, deleted_at
`

type CreateArticleParams struct {
	Title          string
	Slug           string
	Summary        pgtype.Text
	Content        string
	CoverUrl       pgtype.Text
	UserID         int32
	Status         pgtype.Text
	CommentEnabled pgtype.Bool
	ViewCount      int32
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.Content,
		arg.CoverUrl,
		arg.UserID,
		arg.Status,
		arg.CommentEnabled,
		arg.ViewCount,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CoverUrl,
		&i.UserID,
		&i.Status,
		&i.CommentEnabled,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createArticleCategory = `-- name: CreateArticleCategory :exec
INSERT INTO article_categories (article_id, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateArticleCategoryParams struct {
	ArticleID  int32
	CategoryID int32
}

func (q *Queries) CreateArticleCategory(ctx context.Context, arg CreateArticleCategoryParams) error {
	_, err := q.db.Exec(ctx, createArticleCategory, arg.ArticleID, arg.CategoryID)
	return err
}

const createArticleTag = `-- name: CreateArticleTag :exec
INSERT INTO article_tags (article_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateArticleTagParams struct {
	ArticleID int32
	TagID     int32
}

func (q *Queries) CreateArticleTag(ctx context.Context, arg CreateArticleTagParams) error {
	_, err := q.db.Exec(ctx, createArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, description, icon, created_at) VALUES ($1, $2, $3, $4, NOW()) RETURNING id, name, slug, description, icon, created_at
`

type CreateCategoryParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
	Icon        pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (article_id, user_id, content, created_at) VALUES ($1, $2, $3, NOW()) RETURNING id, article_id, user_id, content, created_at, deleted_at
`

type CreateCommentParams struct {
	ArticleID int32
	UserID    pgtype.Int4
	Content   string
}

type CreateCommentRow struct {
	ID        int32
	ArticleID int32
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ArticleID, arg.UserID, arg.Content)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, icon) VALUES ($1, $2, $3) RETURNING id, name, slug, icon
`

type CreateTagParams struct {
	Name string
	Slug string
	Icon pgtype.Text
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Slug, arg.Icon)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
	Avatar       pgtype.Text
	Bio          pgtype.Text
	Group        pgtype.Text
	Status       pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.Bio,
		arg.Group,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Group,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const deleteArticleCategories = `-- name: DeleteArticleCategories :exec
DELETE FROM article_categories WHERE article_id = $1
`

func (q *Queries) DeleteArticleCategories(ctx context.Context, articleID int32) error {
	_, err := q.db.Exec(ctx, deleteArticleCategories, articleID)
	return err
}

const deleteArticleTags = `-- name: DeleteArticleTags :exec
DELETE FROM article_tags WHERE article_id = $1
`

func (q *Queries) DeleteArticleTags(ctx context.Context, articleID int32) error {
	_, err := q.db.Exec(ctx, deleteArticleTags, articleID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at, deleted_at
FROM articles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArticleByID(ctx context.Context, id int32) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CoverUrl,
		&i.UserID,
		&i.Status,
		&i.CommentEnabled,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at, deleted_at
FROM articles WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CoverUrl,
		&i.UserID,
		&i.Status,
		&i.CommentEnabled,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoriesByArticle = `-- name: GetCategoriesByArticle :many
SELECT c.id, c.name, c.slug, c.description, c.icon, c.created_at FROM categories c
INNER JOIN article_categories ac ON c.id = ac.category_id
WHERE ac.article_id = $1
`

func (q *Queries) GetCategoriesByArticle(ctx context.Context, articleID int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, description, icon, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, icon, created_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, article_id, user_id, content, created_at, deleted_at FROM comments WHERE id = $1
`

type GetCommentByIDRow struct {
	ID        int32
	ArticleID int32
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

func (q *Queries) GetCommentByID(ctx context.Context, id int32) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, description FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.Description)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, slug, icon FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, icon FROM tags WHERE slug = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
	)
	return i, err
}

const getTagsByArticle = `-- name: GetTagsByArticle :many
SELECT t.id, t.name, t.slug, t.icon FROM tags t
INNER JOIN article_tags at ON t.id = at.tag_id
WHERE at.article_id = $1
`

func (q *Queries) GetTagsByArticle(ctx context.Context, articleID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at
FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Group,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Group,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at
FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Bio,
		&i.Group,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE articles SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at, deleted_at
FROM articles WHERE deleted_at IS NULL
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CoverUrl,
			&i.UserID,
			&i.Status,
			&i.CommentEnabled,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategory = `-- name: ListArticlesByCategory :many
SELECT a.id, a.title, a.slug, a.summary, a.content, a.cover_url, a.user_id, a.status, a.comment_enabled, a.view_count, a.created_at, a.updated_at, a.deleted_at
FROM articles a
INNER JOIN article_categories ac ON a.id = ac.article_id
WHERE ac.category_id = $1 AND a.deleted_at IS NULL
ORDER BY a.created_at DESC LIMIT $2 OFFSET $3
`

type ListArticlesByCategoryParams struct {
	CategoryID int32
	Limit      int32
	Offset     int32
}

func (q *Queries) ListArticlesByCategory(ctx context.Context, arg ListArticlesByCategoryParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CoverUrl,
			&i.UserID,
			&i.Status,
			&i.CommentEnabled,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByUser = `-- name: ListArticlesByUser :many
SELECT id, title, slug, summary, content, cover_url, user_id, status, comment_enabled, view_count, created_at, updated_at, deleted_at
FROM articles WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListArticlesByUserParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

func (q *Queries) ListArticlesByUser(ctx context.Context, arg ListArticlesByUserParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CoverUrl,
			&i.UserID,
			&i.Status,
			&i.CommentEnabled,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, icon, created_at FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByArticle = `-- name: ListCommentsByArticle :many
SELECT id, article_id, user_id, content, created_at, deleted_at FROM comments
WHERE article_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCommentsByArticleParams struct {
	ArticleID int32
	Limit     int32
	Offset    int32
}

type ListCommentsByArticleRow struct {
	ID        int32
	ArticleID int32
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

func (q *Queries) ListCommentsByArticle(ctx context.Context, arg ListCommentsByArticleParams) ([]ListCommentsByArticleRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByArticleRow
	for rows.Next() {
		var i ListCommentsByArticleRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, description FROM settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, icon FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, nickname, avatar, bio, "group", status, created_at, updated_at
FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Nickname,
			&i.Avatar,
			&i.Bio,
			&i.Group,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value, description) VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = $2, description = $3
`

type SetSettingParams struct {
	Key         string
	Value       []byte
	Description pgtype.Text
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.Exec(ctx, setSetting, arg.Key, arg.Value, arg.Description)
	return err
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles SET title=$1, slug=$2, summary=$3, content=$4, cover_url=$5, status=$6, comment_enabled=$7, updated_at=NOW()
WHERE id=$8 AND deleted_at IS NULL
`

type UpdateArticleParams struct {
	Title          string
	Slug           string
	Summary        pgtype.Text
	Content        string
	CoverUrl       pgtype.Text
	Status         pgtype.Text
	CommentEnabled pgtype.Bool
	ID             int32
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.Content,
		arg.CoverUrl,
		arg.Status,
		arg.CommentEnabled,
		arg.ID,
	)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name=$1, slug=$2, description=$3, icon=$4 WHERE id=$5
`

type UpdateCategoryParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
	Icon        pgtype.Text
	ID          int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.ID,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET name=$1, slug=$2, icon=$3 WHERE id=$4
`

type UpdateTagParams struct {
	Name string
	Slug string
	Icon pgtype.Text
	ID   int32
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET username=$1, email=$2, password_hash=$3, nickname=$4, avatar=$5, bio=$6, "group"=$7, status=$8, updated_at=NOW()
WHERE id=$9
`

type UpdateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Nickname     pgtype.Text
	Avatar       pgtype.Text
	Bio          pgtype.Text
	Group        pgtype.Text
	Status       pgtype.Int4
	ID           int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.Bio,
		arg.Group,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status=$1, updated_at=NOW() WHERE id=$2
`

type UpdateUserStatusParams struct {
	Status pgtype.Int4
	ID     int32
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}
