// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/articles": {
    params: {};
  };
  "/admin/comments": {
    params: {};
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/themes": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/forgot-password" | "/admin" | "/admin/users" | "/admin/articles" | "/admin/comments" | "/admin/categories" | "/admin/settings" | "/admin/themes";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "components/auth-guard.tsx": {
    id: "components/auth-guard";
    page: "/admin" | "/admin/users" | "/admin/articles" | "/admin/comments" | "/admin/categories" | "/admin/settings" | "/admin/themes";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/users" | "/admin/articles" | "/admin/comments" | "/admin/categories" | "/admin/settings" | "/admin/themes";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "routes/admin.articles.tsx": {
    id: "routes/admin.articles";
    page: "/admin/articles";
  };
  "routes/admin.comments.tsx": {
    id: "routes/admin.comments";
    page: "/admin/comments";
  };
  "routes/admin.categories.tsx": {
    id: "routes/admin.categories";
    page: "/admin/categories";
  };
  "routes/admin.settings.tsx": {
    id: "routes/admin.settings";
    page: "/admin/settings";
  };
  "routes/admin.themes.tsx": {
    id: "routes/admin.themes";
    page: "/admin/themes";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "components/auth-guard": typeof import("./app/components/auth-guard.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.users": typeof import("./app/routes/admin.users.tsx");
  "routes/admin.articles": typeof import("./app/routes/admin.articles.tsx");
  "routes/admin.comments": typeof import("./app/routes/admin.comments.tsx");
  "routes/admin.categories": typeof import("./app/routes/admin.categories.tsx");
  "routes/admin.settings": typeof import("./app/routes/admin.settings.tsx");
  "routes/admin.themes": typeof import("./app/routes/admin.themes.tsx");
};